name: assistify
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.2
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.1.5
  intl: ^0.20.2
  printing: ^5.14.2
  share_plus: ^11.0.0
  file_picker: ^10.1.8
  flutter_charts: ^0.5.2
  fl_chart: ^1.0.0
  flutter_bluetooth_printer: ^2.17.1
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: ic_launcher
  ios: true
  image_path: "assets/png/assistify.jpg"

flutter:

  uses-material-design: true
  assets:
    - assets/png/
   
